name: esali
favicon: null
layout_spectrum: 0
typography_spectrum: 0.52889
title: esali - Digital Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f4'
    - '#888a87'
    - '#ef8556'
    - '#75cbcc'
    - '#b6d237'
  brandStrength: 0.375
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
