name: esali
favicon: null
layout_spectrum: 0.0053
typography_spectrum: 0.5203
title: esali - Digital Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b5aba1'
    - '#807767'
    - '#585140'
    - '#f0e9e1'
  brandStrength: 0.625
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
