name: esali
favicon: null
layout_spectrum: 0.98473
typography_spectrum: 0.5085466424934566
title: esali - Digital Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7f7f7f'
    - '#000000'
    - '#93cdde'
    - '#953685'
  brandStrength: 0.5625
  lightness: 0.48541228868998587
  saturation: 0.8990263224113733
  rhythmicContrast: 0.75
purpose: []
