name: esali
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: esali - Digital Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040303'
    - '#e93e91'
    - '#646a67'
    - '#60a5b8'
  brandStrength: 0.5625
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
