name: esali
favicon: null
layout_spectrum: 0.0053
typography_spectrum: 0.5203
title: esali - Digital Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171612'
    - '#a59989'
    - '#716047'
    - '#a3ccb3'
    - '#b62838'
  brandStrength: 0.5625
  lightness: 0.48541228868998587
  saturation: 0.8990263224113733
  rhythmicContrast: 0.75
purpose: []
